"""Initial fraud service migration

Revision ID: 80b35ba7f66f
Revises:
Create Date: 2026-09-14 15:40:36.965001

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "80b35ba7f66f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fraud_assessments",
        sa.Column("assessment_id", sa.String(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("transaction_id", sa.String(), nullable=False),
        sa.Column("risk_score", sa.Float(), nullable=False),
        sa.Column("risk_level", sa.String(), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("assessment_id"),
    )
    op.create_index(
        op.f("ix_fraud_assessments_assessment_id"),
        "fraud_assessments",
        ["assessment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fraud_assessments_event_id"),
        "fraud_assessments",
        ["event_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_fraud_assessments_transaction_id"),
        "fraud_assessments",
        ["transaction_id"],
        unique=False,
    )
    op.create_table(
        "outbox_events",
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("aggregate_type", sa.String(), nullable=False),
        sa.Column("aggregate_id", sa.String(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("schema_version", sa.String(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "processed_events",
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("consumer_group", sa.String(), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("event_id", "consumer_group"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("processed_events")
    op.drop_table("outbox_events")
    op.drop_index(
        op.f("ix_fraud_assessments_transaction_id"), table_name="fraud_assessments"
    )
    op.drop_index(op.f("ix_fraud_assessments_event_id"), table_name="fraud_assessments")
    op.drop_index(
        op.f("ix_fraud_assessments_assessment_id"), table_name="fraud_assessments"
    )
    op.drop_table("fraud_assessments")
    # ### end Alembic commands ###
