global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: banking
    metrics_path: /metrics
    static_configs:
      - targets: ["backend:8000"]
        labels:
          service: banking

  - job_name: fraud
    metrics_path: /metrics
    static_configs:
      - targets: ["fraud:8000"]
        labels:
          service: fraud
