import { ArrowLeft, ArrowUpRight, Landmark } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { useState } from "react";
import { useAccount, useMoneyMutation, useTransactions } from "../lib/queries";
import { apiMessage } from "../lib/api";
import { formatDate, formatMoney } from "../lib/format";
import { Panel } from "../components/ui/Panel";
import { Button } from "../components/ui/Button";
import { Loading, ErrorState, Empty } from "../components/ui/Feedback";
import { Field } from "../components/ui/Field";

export function AccountDetails() { const { accountId } = useParams(); const account = useAccount(accountId); const transactions = useTransactions(accountId); const [amount, setAmount] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const deposit = useMoneyMutation("deposit", accountId ?? ""); const withdraw = useMoneyMutation("withdraw", accountId ?? ""); if (account.isLoading) return <Loading label="Loading account" />; if (account.isError || !account.data) return <ErrorState message={apiMessage(account.error, "Account unavailable.")} />; const data = account.data; async function submit(kind: "deposit" | "withdraw") { setError(""); setMessage(""); const mutation = kind === "deposit" ? deposit : withdraw; try { await mutation.mutateAsync(amount); setAmount(""); setMessage(kind === "deposit" ? "Deposit complete." : "Withdrawal complete."); } catch (err) { setError(apiMessage(err, "The operation could not be completed.")); } }
  return <div><Link className="back-link" to="/accounts"><ArrowLeft size={15} /> Back to accounts</Link><div className="detail-heading"><div><span className="eyebrow">{data.account_type} account</span><h1>•• {data.account_id.slice(-8)}</h1></div><span className="status large"><i />{data.status}</span></div><div className="detail-grid"><Panel className="balance-panel"><span className="eyebrow">Current balance</span><strong>{formatMoney(data.balance)}</strong><div className="detail-meta"><span>Available</span><b>{formatMoney(data.available_balance ?? data.balance)}</b></div><div className="action-line"><Field id="money-amount" label="Amount" placeholder="0.00" inputMode="decimal" value={amount} onChange={(e) => setAmount(e.target.value)} /><div className="action-buttons"><Button onClick={() => void submit("deposit")} disabled={deposit.isPending || withdraw.isPending}>Deposit <ArrowUpRight size={15} /></Button><Button variant="quiet" onClick={() => void submit("withdraw")} disabled={deposit.isPending || withdraw.isPending}>Withdraw</Button></div></div>{message && <div className="alert alert-success">{message}</div>}{error && <div className="alert alert-error">{error}</div>}</Panel><Panel><div className="panel-heading"><div><span className="eyebrow">Account details</span><h2>Terms & status</h2></div><Landmark size={22} /></div><dl className="details-list"><div><dt>Account type</dt><dd>{data.account_type}</dd></div><div><dt>Account status</dt><dd>{data.status}</dd></div>{data.minimum_balance && <div><dt>Minimum balance</dt><dd>{formatMoney(data.minimum_balance)}</dd></div>}{data.overdraft_limit && <div><dt>Overdraft limit</dt><dd>{formatMoney(data.overdraft_limit)}</dd></div>}</dl></Panel></div><Panel className="transactions-panel"><div className="panel-heading"><div><span className="eyebrow">Activity</span><h2>Recent transactions</h2></div><Link className="text-link" to="/transactions">Full history <ArrowUpRight size={15} /></Link></div>{transactions.isLoading ? <Loading label="Loading activity" /> : transactions.isError ? <ErrorState message={apiMessage(transactions.error, "Could not load activity.")} /> : transactions.data?.length ? <TransactionTable items={transactions.data.slice(0, 6)} /> : <Empty title="No activity yet" detail="Deposits, withdrawals, and transfers will appear here." />}</Panel></div>; }

function TransactionTable({ items }: { items: import("../types/api").Transaction[] }) { return <div className="transaction-table">{items.map((item) => <div className="transaction-row" key={item.transaction_id}><span className={`transaction-dot ${item.transaction_type}`} /><div><strong>{item.transaction_type}</strong><small>{formatDate(item.timestamp)}</small></div><strong className={item.transaction_type === "withdrawal" ? "negative" : "positive"}>{item.transaction_type === "withdrawal" ? "−" : "+"}{formatMoney(item.amount)}</strong></div>)}</div>; }
