import { ArrowUpRight, CreditCard, Plus, Send, TrendingUp } from "lucide-react";
import { Link } from "react-router-dom";
import { useAuth } from "../app/AuthContext";
import { apiMessage, api } from "../lib/api";
import { formatMoney } from "../lib/format";
import { useQuery } from "@tanstack/react-query";
import { Panel } from "../components/ui/Panel";
import { Loading, ErrorState, Empty } from "../components/ui/Feedback";
import type { Account } from "../types/api";

export function Dashboard() { const { user } = useAuth(); const accounts = useQuery<Account[]>({ queryKey: ["accounts"], queryFn: async () => (await api.get("/accounts")).data }); if (accounts.isLoading) return <Loading label="Gathering your accounts" />; if (accounts.isError) return <ErrorState message={apiMessage(accounts.error, "Unable to connect to PyBank.")} />; const items = accounts.data ?? []; const total = items.reduce((sum, account) => sum + Number(account.balance), 0); return <div className="dashboard"><div className="page-heading"><div><span className="eyebrow">Tuesday, September 2026</span><h1>Good morning, {user?.email.split("@")[0]}.</h1><p className="muted">Here’s the shape of your money today.</p></div><Link className="button button-primary" to="/transfer"><Send size={17} /> Move money</Link></div><div className="hero-balance"><div><span className="eyebrow">Total across accounts</span><strong>{formatMoney(total)}</strong><span className="balance-note"><TrendingUp size={15} /> Your balances are up to date</span></div><div className="hero-orbit"><span>PB</span></div></div><div className="section-heading"><div><span className="eyebrow">Your money</span><h2>Accounts</h2></div><Link className="text-link" to="/accounts">View all <ArrowUpRight size={15} /></Link></div>{items.length === 0 ? <Panel><Empty title="No accounts yet" detail="Your accounts will appear here once they are created." /></Panel> : <div className="account-grid">{items.map((account) => <Link className="account-card" to={`/accounts/${account.account_id}`} key={account.account_id}><div className="card-top"><span className={`account-icon ${account.account_type}`}><CreditCard size={19} /></span><span className="status"><i />{account.status}</span></div><span className="account-label">{account.account_type} account</span><strong>{formatMoney(account.balance)}</strong><span className="account-id">•• {account.account_id.slice(-8)}</span></Link>)}<Link className="account-card add-card" to="/accounts"><Plus size={22} /><span>Manage accounts</span></Link></div>}</div>; }
