import { useQuery } from "@tanstack/react-query";
import { api, apiMessage } from "../lib/api";
import { formatDate, formatMoney } from "../lib/format";
import { Loading, ErrorState, Empty } from "../components/ui/Feedback";
import { Panel } from "../components/ui/Panel";
import type { Account, Transaction } from "../types/api";

export function Transactions() { const accounts = useQuery<Account[]>({ queryKey: ["accounts"], queryFn: async () => (await api.get("/accounts")).data }); const [selected, setSelected] = React.useState(""); const accountId = selected || accounts.data?.[0]?.account_id; const history = useQuery<Transaction[]>({ queryKey: ["transactions", accountId], queryFn: async () => (await api.get(`/accounts/${accountId}/transactions`)).data, enabled: Boolean(accountId) }); if (accounts.isLoading) return <Loading label="Loading accounts" />; if (accounts.isError) return <ErrorState message={apiMessage(accounts.error, "Unable to load your accounts.")} />; return <div><div className="page-heading"><div><span className="eyebrow">Ledger</span><h1>Transactions</h1><p className="muted">A record of movement across your accounts.</p></div><select className="select" value={accountId ?? ""} onChange={(e) => setSelected(e.target.value)}>{accounts.data?.map((account) => <option key={account.account_id} value={account.account_id}>{account.account_type} · •• {account.account_id.slice(-8)}</option>)}</select></div><Panel>{history.isLoading ? <Loading label="Loading transactions" /> : history.isError ? <ErrorState message={apiMessage(history.error, "Could not load transactions.")} /> : history.data?.length ? <div className="transaction-table">{history.data.map((item) => <div className="transaction-row" key={item.transaction_id}><span className={`transaction-dot ${item.transaction_type}`} /><div><strong>{item.transaction_type}</strong><small>{formatDate(item.timestamp)} · {item.status}</small></div><strong className={item.transaction_type === "withdrawal" ? "negative" : "positive"}>{item.transaction_type === "withdrawal" ? "−" : "+"}{formatMoney(item.amount)}</strong></div>)}</div> : <Empty title="No transactions" detail="This account has no recorded activity yet." />}</Panel></div>; }
import React from "react";
