import { ArrowDownUp, CheckCircle2 } from "lucide-react";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api, apiMessage } from "../lib/api";
import type { Account } from "../types/api";
import { Panel } from "../components/ui/Panel";
import { Button } from "../components/ui/Button";
import { Field } from "../components/ui/Field";
import { Loading, ErrorState } from "../components/ui/Feedback";
import { formatMoney } from "../lib/format";

export function Transfer() { const queryClient = useQueryClient(); const accounts = useQuery<Account[]>({ queryKey: ["accounts"], queryFn: async () => (await api.get("/accounts")).data }); const [source, setSource] = useState(""); const [destination, setDestination] = useState(""); const [amount, setAmount] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const mutation = useMutation({ mutationFn: async () => (await api.post("/transfers", { source_account_id: source, destination_account_id: destination, amount })).data, onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ["accounts"] }); setMessage("Transfer complete. Both account balances are up to date."); setAmount(""); } }); if (accounts.isLoading) return <Loading label="Loading accounts" />; if (accounts.isError) return <ErrorState message="Unable to load your accounts." />; const items = accounts.data ?? []; async function submit(event: React.FormEvent) { event.preventDefault(); setMessage(""); setError(""); try { await mutation.mutateAsync(); } catch (err) { setError(apiMessage(err, "The transfer could not be completed.")); } }
  return <div className="narrow-page"><div className="page-heading"><div><span className="eyebrow">Payments</span><h1>Move money</h1><p className="muted">Transfer between accounts you own.</p></div><span className="transfer-badge"><ArrowDownUp size={16} /> Secure transfer</span></div><Panel><form className="stack" onSubmit={submit}><label className="field"><span>From account</span><select className="select" value={source} onChange={(e) => setSource(e.target.value)} required><option value="">Choose an account</option>{items.map((account) => <option key={account.account_id} value={account.account_id}>{account.account_type} · {formatMoney(account.balance)}</option>)}</select></label><label className="field"><span>To account</span><select className="select" value={destination} onChange={(e) => setDestination(e.target.value)} required><option value="">Choose an account</option>{items.filter((account) => account.account_id !== source).map((account) => <option key={account.account_id} value={account.account_id}>{account.account_type} · •• {account.account_id.slice(-8)}</option>)}</select></label><Field id="transfer-amount" label="Amount" placeholder="0.00" inputMode="decimal" value={amount} onChange={(e) => setAmount(e.target.value)} required />{error && <div className="alert alert-error">{error}</div>}{message && <div className="alert alert-success"><CheckCircle2 size={17} />{message}</div>}<Button type="submit" disabled={mutation.isPending}>{mutation.isPending ? "Sending…" : "Review & send"}<ArrowDownUp size={17} /></Button></form></Panel></div>; }
